[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["src/**", "*.json", "*.html", "*.toml"]

[deploy]
startCommand = "npx serve -s dist -l $PORT"
restartPolicyType = "ON_FAILURE"
numReplicas = 1
